import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

import {
  normalizeOrchestratorPrinterInventory,
  OrchestratorError,
} from "./client";

/**
 * Runtime contract between atelier's printer-inventory DTO
 * (`GET /api/printers/inventory`) and this client's validator. The fixture is
 * generated by the orchestrator's own contract test
 * (apps/atelier/apps/print-orchestrator/src/domain/printers/inventory.contract.test.ts,
 * `UPDATE_CONTRACT=1 pnpm test`) and committed VERBATIM in both repos, because
 * the projects build and deploy independently — matching TypeScript types alone
 * prove nothing across that boundary.
 *
 * This is the contract that decides where work may be sent, so what it pins is
 * as much about what must NOT be there (credentials, device addresses) as about
 * what must.
 */
const LOCAL_FIXTURE = path.resolve(__dirname, "printer-inventory.contract.json");

/** The atelier copy: env override first, then the standard sibling layout. */
function atelierFixturePath(): string | null {
  const fromEnv = process.env.ATELIER_PRINTER_INVENTORY_CONTRACT?.trim();
  if (fromEnv) return fromEnv;

  const sibling = path.resolve(
    __dirname,
    "../../../../../../../atelier/apps/print-orchestrator/contracts/printer-inventory.contract.json"
  );
  return existsSync(sibling) ? sibling : null;
}

function loadFixture(): Record<string, unknown> {
  return JSON.parse(readFileSync(LOCAL_FIXTURE, "utf8"));
}

test("the committed inventory payload passes the runtime validator", () => {
  const inventory = normalizeOrchestratorPrinterInventory(loadFixture());

  assert.equal(inventory.printers.length, 3);
  assert.match(inventory.revision, /^[0-9a-f]{16}$/);

  const [first] = inventory.printers;
  assert.equal(first.id, "contract-printer");
  assert.equal(first.name, "Contract Printer");
  assert.equal(first.model, "Contract 3000");
  assert.equal(first.type, "FDM");
  assert.equal(first.printerClass, "contract-class");
  assert.equal(first.protocol, "moonraker");
  assert.equal(first.enabled, true);
  assert.equal(first.material, "PETG");
  assert.equal(first.nozzleDiameterMm, 0.4);
  assert.equal(first.nozzleType, "hardened_steel");
  assert.deepEqual(first.buildVolume, { x: 220, y: 220, z: 250 });
  assert.equal(first.version, 3);
});

test("a disabled printer arrives flagged, not missing", () => {
  const inventory = normalizeOrchestratorPrinterInventory(loadFixture());
  const disabled = inventory.printers.find(
    (printer) => printer.id === "contract-disabled"
  );

  assert.ok(disabled, "the contract must carry disabled printers");
  assert.equal(disabled.enabled, false);
  // Which is the whole point: without it, "switched off" and "deleted" would be
  // the same observation here.
  assert.notEqual(disabled.enabled, undefined);
});

test("unspecified configuration arrives as null, never as an empty string", () => {
  const inventory = normalizeOrchestratorPrinterInventory(loadFixture());
  const minimal = inventory.printers.find(
    (printer) => printer.id === "contract-minimal"
  );

  assert.ok(minimal);
  assert.equal(minimal.model, null);
  assert.equal(minimal.printerClass, null);
  assert.equal(minimal.material, null);
  assert.equal(minimal.nozzleDiameterMm, null);
  assert.equal(minimal.nozzleType, null);
  assert.equal(minimal.buildVolume, null);
});

test("the inventory contract never carries connection parameters or credentials", () => {
  const forbidden = [
    "host",
    "port",
    "apiKey",
    "serial",
    "accessCode",
    "allowInsecureTls",
    "snapshotUrl",
    "streamUrl",
    "interfaceUrl",
    "light",
    "secrets",
  ];

  const fixture = loadFixture() as { printers: Array<Record<string, unknown>> };
  for (const printer of fixture.printers) {
    for (const key of forbidden) {
      assert.ok(
        !(key in printer),
        `forbidden field "${key}" appeared in the printer inventory contract`
      );
    }
  }
});

test("a payload without a revision is refused", () => {
  const fixture = loadFixture();
  delete fixture.revision;

  assert.throws(
    () => normalizeOrchestratorPrinterInventory(fixture),
    (error: unknown) =>
      error instanceof OrchestratorError && error.kind === "invalid_response"
  );
});

test("the local fixture copy matches the atelier checkout (when present)", (t) => {
  const atelierPath = atelierFixturePath();
  if (!atelierPath || !existsSync(atelierPath)) {
    t.skip("atelier checkout not found — verbatim-copy check skipped");
    return;
  }

  assert.equal(
    readFileSync(LOCAL_FIXTURE, "utf8"),
    readFileSync(atelierPath, "utf8"),
    "printer-inventory.contract.json diverged between the repos. Regenerate in " +
      "atelier (UPDATE_CONTRACT=1 pnpm test) and copy it here verbatim."
  );
});
